### ISSUE TITLE
Mining dimension biome properites are being shuffled with other modded biomes.

### ISSUE THREAD

**Issue by seanimusprime** [henkelmax/advanced-mining-dimension#59]
**Please read the [FAQ](https://modrepo.de/minecraft/mining_dimension/faq) before submitting a bug report!**

**Bug description**
Some modded biomes are overriding the mining dimension properties (ambient sounds, water color, fog color, mob spawning, etc), specifically from the mods The Bumblezone and BetterNether Reforged. To be clear, the biomes themselves are not spawning in the dimension, only that the mining dimension "biomes" are inheriting the properties of said biomes.

**Steps to reproduce the issue**
1. Install Bumblezone, BetterNether Reforged, and "henkelmax advanced-mining-dimension master datapacks-no_mobs.zip" datapack.
2. Start world and visit the mining dimension.
3. Even though no mobs are supposed to be spawning, we now have bees and zombie piglins spawning, as well as an annoying buzzing ambient sound, colored fog effects, and yellow water.

**Expected behavior**
The mining dimension to have no mob spawning and have regular, vanilla biome properties.

**Log files**
No log files to produce as no error is actually occurring.

**Versions**
- Minecraft version 1.16.5
- Forge version 36.2.6
- Mod version 1.0.5

**Other mods**
The BumbleZone
BetterNether Reforged

Also added
Biome ID Fixer and Chocolate Fix to see if they would fix the issue. They did not.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
There's nothing I can do about that. My mod is basically just a datapack with a teleporter block. It is really the fault of these mods programmatically injecting their spawns into the biomes. Maybe they have a config to stop these mobs from spawning in all biomes.

**Comment by TelepathicGrunt** [comment]
@seanimusprime i am not programmingly injecting spawns into your biomes so don’t be quick to blame me lol. This sounds more like the biome id shuffling bug that occurs when new biomes are added by datapack or mod. Forge should’ve fixed this vanilla bug a while ago from happening which is odd. I mentioned a bit more details on the report on my GitHub repo

**Comment by henkelmax** [comment]
But in any case, this is not an issue of this mod since it just adds the dimension via a datapack.

**Comment by TelepathicGrunt** [comment]
Just double checking your dimension’s json file, I noticed you are using "minecraft:fixed" biome source. You need to switch that out because the fixed biome source is actually broken for biomes. It doesn’t hold the dynamic registry biome iirc and it has issues syncing it to the client. Instead, try switching this to multi noise biome source and give it only your mining dimension biome. I can make a datapack for this user to test to see if that fixed biomes source was the cause (part of Mc will grab the biome at an already generated spot from the biome source instead of the chunk so if the biome source’s output shifts, it can cause weird stuff)

**Comment by seanimusprime** [comment]
> Just double checking your dimension’s json file, I noticed you are using "minecraft:fixed" biome source. You need to switch that out because the fixed biome source is actually broken for biomes. It doesn’t hold the dynamic registry biome iirc and it has issues syncing it to the client. Instead, try switching this to multi noise biome source and give it only your mining dimension biome. I can make a datapack for this user to test to see if that fixed biomes source was the cause (part of Mc will grab the biome at an already generated spot from the biome source instead of the chunk so if the biome source’s output shifts, it can cause weird stuff)

I'd be more than happy to test out a datapack. I appreciate any all help with this.

**Comment by TelepathicGrunt** [comment]
Alright so doing some testing myself, I put on mining dimension, created world and go to mining dimension itself. Clicked F3 and saw the biome entry was stuck on "waiting for chunk".

Then I put on the no mob datapack and as many biomes mods as I could (bumblezone, incendium, byg, bop, and better nether reforged). Entered the same world from before and now F3 is showing byg:ebony_hills with their fog 
![image](https://user-images.githubusercontent.com/40846040/135759723-90c5ff11-3dba-4a23-8124-92b5a81e8bed.png)


I tried changing mining dimension's json to this:
```
{
  "generator": {
    "type": "minecraft:noise",
    "biome_source": {
      "seed": 0,
      "type": "minecraft:multi_noise",
      "biomes": [
        {
          "biome": "mining_dimension:mining",
          "parameters": { "altitude": 0.0, "weirdness": 0.0, "offset": 0.0, "temperature": 0.0, "humidity": 0.0 }
        }
      ],
      "humidity_noise": { "firstOctave": -7, "amplitudes": [ 1.0, 1.0 ] },
      "altitude_noise": { "firstOctave": -7, "amplitudes": [ 1.0, 1.0 ] },
      "weirdness_noise": { "firstOctave": -7, "amplitudes": [ 1.0, 1.0 ] },
      "temperature_noise": { "firstOctave": -7, "amplitudes": [ 1.0, 1.0 ] }
    },
    "seed": 0,
    "settings": "mining_dimension:mining"
  },
  "type": "mining_dimension:mining"
}
```

But it doesn't seem to correct the biomes which leaves me stumped. The new chunks are mining dimension biomes just fine. It's just the old already generated chunks that are shifted then so that rules out the fixed biome source (although it does have it's own fair share of problems listed on the mojang bug tracker https://bugs.mojang.com/browse/MC-197616)

@seanimusprime Your best bet right now is to just delete the chunks from the mining dimension itself by editing the region files for the dimension. That way the chunks are remade with the correct biome id when you have all the biome mods on that you want. Sorry

**Comment by seanimusprime** [comment]
> Alright so doing some testing myself, I put on mining dimension, created world and go to mining dimension itself. Clicked F3 and saw the biome entry was stuck on "waiting for chunk".
> 
> Then I put on the no mob datapack and as many biomes mods as I could (bumblezone, incendium, byg, bop, and better nether reforged). Entered the same world from before and now F3 is showing byg:ebony_hills with their fog ![image](https://user-images.githubusercontent.com/40846040/135759723-90c5ff11-3dba-4a23-8124-92b5a81e8bed.png)
> 
> I tried changing mining dimension's json to this:
> 
> ```
> {
>   "generator": {
>     "type": "minecraft:noise",
>     "biome_source": {
>       "seed": 0,
>       "type": "minecraft:multi_noise",
>       "biomes": [
>         {
>           "biome": "mining_dimension:mining",
>           "parameters": { "altitude": 0.0, "weirdness": 0.0, "offset": 0.0, "temperature": 0.0, "humidity": 0.0 }
>         }
>       ],
>       "humidity_noise": { "firstOctave": -7, "amplitudes": [ 1.0, 1.0 ] },
>       "altitude_noise": { "firstOctave": -7, "amplitudes": [ 1.0, 1.0 ] },
>       "weirdness_noise": { "firstOctave": -7, "amplitudes": [ 1.0, 1.0 ] },
>       "temperature_noise": { "firstOctave": -7, "amplitudes": [ 1.0, 1.0 ] }
>     },
>     "seed": 0,
>     "settings": "mining_dimension:mining"
>   },
>   "type": "mining_dimension:mining"
> }
> ```
> 
> But it doesn't seem to correct the biomes which leaves me stumped. The new chunks are mining dimension biomes just fine. It's just the old already generated chunks that are shifted then so that rules out the fixed biome source (although it does have it's own fair share of problems listed on the mojang bug tracker https://bugs.mojang.com/browse/MC-197616)
> 
> @seanimusprime Your best bet right now is to just delete the chunks from the mining dimension itself by editing the region files for the dimension. That way the chunks are remade with the correct biome id when you have all the biome mods on that you want. Sorry

I appreciate the help. As we have really have nothing important in the mining dimension, I'll probably just wipe the entire folder and generate a fresh dimension. Thank you for looking into it, because I don't have any idea where to even begin.
