### ISSUE TITLE
1.19.2 - Spawn rates of modded ores in datapack

### ISSUE THREAD

**Issue by PaulSumner-Sage** [henkelmax/advanced-mining-dimension#69]
Now that I've gotten a 1.19.2 datapack working to reduce/control which mobs spawn in the mining dimension: the next issue I'm havinbg is gettign modded ores to spawn **at all** reasonably.
At first I was sure that they weren't spawning at all: but I've since found *very* small quantities spawning in chunks.

I'm using Mekanism and immersive engineering, whose ores I'm mostly inerested in, but there are others such as RFTools and survivalplus.

Can you give any guidance on how to affect the spawn rates of ores in the mining dimension in a datapack for 1.19.2? 
The approach used in the 1,16 data files appears not to work anymore: and didn't show/docuemnt how to do so for modded ores.

I presume using one of these is the correct format to reference an example ore:

- `"forge:osmium_ore"`
- `"forge:ore_osmium"`
- `"mekanism:osmium_ore"`
- `"mekanism:ore_osmium"`

But even knowing _how_ to refernce teh ore: I don;t know where to put a value or what to set to increase/affect spawnrates of ores in this dimension.

I've edited the config->adlods->Deposits->ORE_NAME.cfg files to allow the mining dimension in their whitelist:
```
S:whiteList <
  minecraft:overworld
  mining_dimension:mining
>
```
But this appeared to have no effect on ore appearing (most in that folder do not spawn so far as I have found)

If modded ores are a no for help: advice on how to change spawn rates of a vanilla ore could help. (Pick any as an example, Iron/Gold/RedStone etc)

Any advice is helpful and appreciated. Any data/settings you need please let me know.

**Comment by PaulSumner-Sage** [comment]
Pressed enter early. Will edit 🤦🏻

**Comment by henkelmax** [comment]
I can't help you with that. This is vanilla minecraft datapack stuff, sorry.

**Comment by PaulSumner-Sage** [comment]
Thanks for the quick reply: Any luck with my followup question?

> If modded ores are a no for help: advice on how to change spawn rates of a vanilla ore could help. (Pick any as an example, Iron/Gold/RedStone etc)

**Comment by Daltaxy** [comment]
> Thanks for the quick reply: Any luck with my followup question?
> 
> > If modded ores are a no for help: advice on how to change spawn rates of a vanilla ore could help. (Pick any as an example, Iron/Gold/RedStone etc)
> > Any advice is helpful and appreciated. Any data/settings you need please let me know.

hey. Personally, I added modded ores. I was too lazy to post in the github how to do it though, because it already took me a lot of time to customize everything in 1.19.2.
Please use https://misode.github.io/worldgen/biome/ to modify the ores that you want to add, as well as the monsters and mobs you want in the dimension. All of the modded ores do not work and I didn't bother finding a fix.
Mystical Agriculture ores work perfectly though. Also don't forget to remove your mining dimension in the server folder to allow the world to regenerate.
You can change many things in that website, and include them in your datapack.
What I recommend you to do is to take the 1.19.2 file, copy its content into the linked website (bottom right, select all and replace it with the mining dimension text) and then just add whatever you want to add.
Anyways, the website is incredibly useful. you can change whatever you want.
Don't forget to use the right 1.19.2 datapack, not the examples that are outdated.
Here are mine containing mobs from The Graveyard and modded ores (Mystical Agriculture only). Note that some mods automatically will spawn their ores in the dimension, despite not being included in the datapack. Immersive Engineering is one of them I believe.
https://mega.nz/file/4IZXDLAA#GUN53_L3z_dCUpDwxrFRDSuuMq7dnDYzLAUUZHNSM-k
The file you want is default\data\mining_dimension\worldgen\biome\mining.json
Ignore the .bak files, they are created by my notepad.
